### ISSUE TITLE
Need "accept_license" parameter for win_psmodule

### ISSUE THREAD

**Issue by mattgagliardi** [justin-p/ansible-role-wincom#4]
It seems as though roles (pdc) relying on the wincom role are failing due to it not including "accept_license: true" variable.

**Comment by justin-p** [comment]
Hi @mattgagliardi,

I'm currently unable to test this, but PR #5 should fix it. Are you able to verify this ?

Thanks!

**Comment by mattgagliardi** [comment]
Justin,

  Yup, that change got it in wincom. Module is also referenced over in pdc so I changed it there too, now I’m rolling along. Thanks!

Matt

On Feb 2, 2023, at 4:12 PM, Justin Perdok ***@***.***> wrote:

﻿

Hi @mattgagliardi<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmattgagliardi&data=05%7C01%7C%7Cfa367695690d4bdc121408db056a97ef%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638109727604599028%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1ILsJMlliDZCrmPs3nVrLHwzSrdoJrzjfqgV4LoB9CA%3D&reserved=0>,

I'm currently unable to test this, but PR #5<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjustin-p%2Fansible-role-wincom%2Fpull%2F5&data=05%7C01%7C%7Cfa367695690d4bdc121408db056a97ef%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638109727604599028%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=92z1G3JxxkDjRlulN8xd4yK6zciMxhhdthtTGZmxJYU%3D&reserved=0> should fix it. Are you able to verify this ?

Thanks!

**Comment by justin-p** [comment]
Should be fixed in most recent versions of the roles.
